### ISSUE TITLE
Can't run lpc_checksum

### ISSUE THREAD

**Issue by libcg** [basilfx/lpc_checksum#1]
`sudo pip install lpc_checksum`
`lpc_checksum mybinary.bin`
-> `Error: ord() expected string of length 1, but int found`

Running on Python 3.7

**Comment by libcg** [comment]
Changing line 78 to `block = bytearray(handle.gets(BLOCK_START, BLOCK_TOTAL))` seems to fix it.

**Comment by libcg** [comment]
this is a intehex regression: https://github.com/bialix/intelhex/commit/4722987857589263a7a1358522065307d4b92fa7

**Comment by basilfx** [comment]
Thanks for reporting. It's fixed in release 2.1.1.
