### ISSUE TITLE
Tool computes incorrect checksum on internal 32-bit overflow

### ISSUE THREAD

**Issue by maxgerhardt** [basilfx/lpc_checksum#2]
In your script you attempt to do a 32-bit unsigned add in python.

https://github.com/basilfx/lpc_checksum/blob/14ff53e8256a8dbe6dc7f3ecf9a0d50646a4f044/lpc_checksum.py#L88

However, when an overflow occurrs, meaning the result is larger than 32 bits, the upper bits are discarded by the CPU and only the lower 32 bits are retained. Thus it's wrong to do modulo, there should be an `AND`. For reference, see https://stackoverflow.com/a/210747/5296568

Example: The [original program](https://github.com/microbuilder/LPC1343CodeBase/blob/master/tools/lpcrc/lpcrc.c) and your script compute different values for [this firmware.bin](http://www.mediafire.com/file/h82uceo734rhio8/firmware.bin/file). 

```
gcc -o lpcrc lpcrc.c && lpcrc.exe firmware.bin && python lpcrc.py firmware.bin
-- lpcrc.exe --
succesfully updated crc to: 02b6aa66
-- lpcrc.py --
Firmware path: firmware.bin
Wrote checksum 0x2b6aa63 into binary.
```

When patching it with the python script, `openocd` complains 

```
** Programming Started **
Warn : Verification will fail since checksum in image (0x02b6aa63) to be written to flash is different from calculated vector checksum (0x02b6aa66).
Warn : To remove this warning modify build tools on developer PC to inject correct LPC vector checksum.
** Programming Finished **
** Verify Started **
Error: checksum mismatch - attempting binary compare
embedded:startup.tcl:449: Error: ** Verify Failed **
```

The script returns the same checksum as the C program after applying the patch above for `&` instead of `%`.

**Comment by basilfx** [comment]
Thanks for raising this issue. I'll be honest that I never encountered this case (or at least never noticed it).

I've committed v2.1.2 that includes the fix (and a test case with the binary provided). I'll release that one soon on PyPi.
